/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;

/**
 *
 * @author Jesus
 */
public class frmCuentaAhorros extends javax.swing.JFrame {
    int xMouse, yMouse;

    /**
     * Creates new form frmCuentaAhorros
     */
    public frmCuentaAhorros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPrincipal = new javax.swing.JPanel();
        panelDeOpciones = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnRegistroCuenta = new javax.swing.JPanel();
        btnRegistroCuenta1 = new javax.swing.JLabel();
        btnActualizarCuenta = new javax.swing.JPanel();
        btnActualizarCuenta1 = new javax.swing.JLabel();
        btnEliminarCuenta = new javax.swing.JPanel();
        btnEliminarCuentas = new javax.swing.JLabel();
        btnListadosdeCuentas = new javax.swing.JPanel();
        btnListadoDeCuentas = new javax.swing.JLabel();
        btnNuevoMovimiento = new javax.swing.JPanel();
        btnNuevoMovimiento1 = new javax.swing.JLabel();
        btnMovimientos = new javax.swing.JPanel();
        lblMovimiento = new javax.swing.JLabel();
        btnEditarMovimiento = new javax.swing.JPanel();
        lblEditarMovimiento = new javax.swing.JLabel();
        btnConexion = new javax.swing.JPanel();
        lblConexion = new javax.swing.JLabel();
        btnCerrarAplicacion = new javax.swing.JPanel();
        btnCerrarApp = new javax.swing.JPanel();
        btnCerrarApp1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        backgroundPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDeOpciones.setBackground(new java.awt.Color(255, 204, 102));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChatGPT_Image_5_jun_2025__18_18_51-removebg-preview.png"))); // NOI18N

        btnRegistroCuenta.setBackground(new java.awt.Color(255, 204, 102));
        btnRegistroCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroCuentaMouseExited(evt);
            }
        });

        btnRegistroCuenta1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnRegistroCuenta1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroCuenta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistroCuenta1.setText("Registro Cuentas");
        btnRegistroCuenta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroCuenta1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnRegistroCuentaLayout = new javax.swing.GroupLayout(btnRegistroCuenta);
        btnRegistroCuenta.setLayout(btnRegistroCuentaLayout);
        btnRegistroCuentaLayout.setHorizontalGroup(
            btnRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRegistroCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistroCuenta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnRegistroCuentaLayout.setVerticalGroup(
            btnRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistroCuenta1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        btnActualizarCuenta.setBackground(new java.awt.Color(255, 204, 102));
        btnActualizarCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarCuentaMouseExited(evt);
            }
        });

        btnActualizarCuenta1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnActualizarCuenta1.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarCuenta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizarCuenta1.setText("Actualizar Cuentas");

        javax.swing.GroupLayout btnActualizarCuentaLayout = new javax.swing.GroupLayout(btnActualizarCuenta);
        btnActualizarCuenta.setLayout(btnActualizarCuentaLayout);
        btnActualizarCuentaLayout.setHorizontalGroup(
            btnActualizarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnActualizarCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActualizarCuenta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnActualizarCuentaLayout.setVerticalGroup(
            btnActualizarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarCuenta1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        btnEliminarCuenta.setBackground(new java.awt.Color(255, 204, 102));
        btnEliminarCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarCuentaMouseExited(evt);
            }
        });

        btnEliminarCuentas.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnEliminarCuentas.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCuentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarCuentas.setText("Eliminar Cuentas");
        btnEliminarCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCuentasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarCuentaLayout = new javax.swing.GroupLayout(btnEliminarCuenta);
        btnEliminarCuenta.setLayout(btnEliminarCuentaLayout);
        btnEliminarCuentaLayout.setHorizontalGroup(
            btnEliminarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminarCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnEliminarCuentaLayout.setVerticalGroup(
            btnEliminarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnListadosdeCuentas.setBackground(new java.awt.Color(255, 204, 102));
        btnListadosdeCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListadosdeCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListadosdeCuentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListadosdeCuentasMouseExited(evt);
            }
        });

        btnListadoDeCuentas.setBackground(new java.awt.Color(255, 204, 102));
        btnListadoDeCuentas.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnListadoDeCuentas.setForeground(new java.awt.Color(255, 255, 255));
        btnListadoDeCuentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnListadoDeCuentas.setText("Listado de Cuentas");
        btnListadoDeCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListadoDeCuentasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnListadosdeCuentasLayout = new javax.swing.GroupLayout(btnListadosdeCuentas);
        btnListadosdeCuentas.setLayout(btnListadosdeCuentasLayout);
        btnListadosdeCuentasLayout.setHorizontalGroup(
            btnListadosdeCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListadoDeCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnListadosdeCuentasLayout.setVerticalGroup(
            btnListadosdeCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListadoDeCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        btnNuevoMovimiento.setBackground(new java.awt.Color(255, 204, 102));
        btnNuevoMovimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnNuevoMovimiento1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnNuevoMovimiento1.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoMovimiento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNuevoMovimiento1.setText("Nuevo Movimiento");
        btnNuevoMovimiento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMovimiento1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnNuevoMovimientoLayout = new javax.swing.GroupLayout(btnNuevoMovimiento);
        btnNuevoMovimiento.setLayout(btnNuevoMovimientoLayout);
        btnNuevoMovimientoLayout.setHorizontalGroup(
            btnNuevoMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNuevoMovimiento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNuevoMovimientoLayout.setVerticalGroup(
            btnNuevoMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNuevoMovimiento1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        btnMovimientos.setBackground(new java.awt.Color(255, 204, 102));
        btnMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovimientosMouseClicked(evt);
            }
        });

        lblMovimiento.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblMovimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblMovimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovimiento.setText("Movimiento");

        javax.swing.GroupLayout btnMovimientosLayout = new javax.swing.GroupLayout(btnMovimientos);
        btnMovimientos.setLayout(btnMovimientosLayout);
        btnMovimientosLayout.setHorizontalGroup(
            btnMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnMovimientosLayout.setVerticalGroup(
            btnMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        btnEditarMovimiento.setBackground(new java.awt.Color(255, 204, 102));
        btnEditarMovimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarMovimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMovimientoMouseClicked(evt);
            }
        });

        lblEditarMovimiento.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblEditarMovimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblEditarMovimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditarMovimiento.setText("Editar Movimiento");

        javax.swing.GroupLayout btnEditarMovimientoLayout = new javax.swing.GroupLayout(btnEditarMovimiento);
        btnEditarMovimiento.setLayout(btnEditarMovimientoLayout);
        btnEditarMovimientoLayout.setHorizontalGroup(
            btnEditarMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditarMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEditarMovimientoLayout.setVerticalGroup(
            btnEditarMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditarMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        btnConexion.setBackground(new java.awt.Color(255, 204, 102));
        btnConexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConexionMouseClicked(evt);
            }
        });

        lblConexion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblConexion.setForeground(new java.awt.Color(255, 255, 255));
        lblConexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConexion.setText("Conexión");

        javax.swing.GroupLayout btnConexionLayout = new javax.swing.GroupLayout(btnConexion);
        btnConexion.setLayout(btnConexionLayout);
        btnConexionLayout.setHorizontalGroup(
            btnConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnConexionLayout.setVerticalGroup(
            btnConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConexion, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDeOpcionesLayout = new javax.swing.GroupLayout(panelDeOpciones);
        panelDeOpciones.setLayout(panelDeOpcionesLayout);
        panelDeOpcionesLayout.setHorizontalGroup(
            panelDeOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistroCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnActualizarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEliminarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDeOpcionesLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(panelDeOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListadosdeCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelDeOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDeOpcionesLayout.setVerticalGroup(
            panelDeOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeOpcionesLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListadosdeCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        backgroundPrincipal.add(panelDeOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 330, 820));

        btnCerrarAplicacion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarAplicacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnCerrarAplicacionMouseDragged(evt);
            }
        });
        btnCerrarAplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarAplicacionMousePressed(evt);
            }
        });

        btnCerrarApp.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarAppMouseClicked(evt);
            }
        });

        btnCerrarApp1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnCerrarApp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarApp1.setText("X");
        btnCerrarApp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnCerrarAppLayout = new javax.swing.GroupLayout(btnCerrarApp);
        btnCerrarApp.setLayout(btnCerrarAppLayout);
        btnCerrarAppLayout.setHorizontalGroup(
            btnCerrarAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarApp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );
        btnCerrarAppLayout.setVerticalGroup(
            btnCerrarAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarApp1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnCerrarAplicacionLayout = new javax.swing.GroupLayout(btnCerrarAplicacion);
        btnCerrarAplicacion.setLayout(btnCerrarAplicacionLayout);
        btnCerrarAplicacionLayout.setHorizontalGroup(
            btnCerrarAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarAplicacionLayout.createSequentialGroup()
                .addGap(0, 739, Short.MAX_VALUE)
                .addComponent(btnCerrarApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCerrarAplicacionLayout.setVerticalGroup(
            btnCerrarAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        backgroundPrincipal.add(btnCerrarAplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 800, 50));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡HOLA TRALALERO TRALALA!");
        backgroundPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 790, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mangojiji (1).jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sleiman.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        backgroundPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gonzalo cancer.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gonzalo bw.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gonzalo descuido.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gonzalo intellijet.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gonzalo shrek.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gonzalo surprise.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/meme moeruan.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 660, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/muerano.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/galvez.png"))); // NOI18N
        backgroundPrincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel12.setText("¡PURO ALUMNO DEL PROFESOR GALVEZ!");
        backgroundPrincipal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, 360, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bombadino crocodrilo.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tralalero-tralala-shark.gif"))); // NOI18N
        backgroundPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boing de mango.jpg"))); // NOI18N
        backgroundPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroCuentaMouseEntered
        btnRegistroCuenta.setBackground(new Color(255,69,0));
    }//GEN-LAST:event_btnRegistroCuentaMouseEntered

    private void btnRegistroCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroCuentaMouseExited
        btnRegistroCuenta.setBackground(new Color(255,204,102));
    }//GEN-LAST:event_btnRegistroCuentaMouseExited

    private void btnActualizarCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarCuentaMouseEntered
        btnActualizarCuenta.setBackground(new Color(255,69,0));
    }//GEN-LAST:event_btnActualizarCuentaMouseEntered

    private void btnActualizarCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarCuentaMouseExited
        btnActualizarCuenta.setBackground(new Color(255,204,102));
    }//GEN-LAST:event_btnActualizarCuentaMouseExited

    private void btnEliminarCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCuentaMouseEntered
        btnEliminarCuenta.setBackground(new Color(255,69,0));
    }//GEN-LAST:event_btnEliminarCuentaMouseEntered

    private void btnEliminarCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCuentaMouseExited
        btnEliminarCuenta.setBackground(new Color(255,204,102));
    }//GEN-LAST:event_btnEliminarCuentaMouseExited

    private void btnRegistroCuenta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroCuenta1MouseClicked
        frmRegistroCuenta ventana= new frmRegistroCuenta();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnRegistroCuenta1MouseClicked

    private void btnCerrarAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarAppMouseClicked
        System.exit(0);        
    }//GEN-LAST:event_btnCerrarAppMouseClicked

    private void btnListadosdeCuentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListadosdeCuentasMouseEntered
        btnListadosdeCuentas.setBackground(new Color(255,69,0));
    }//GEN-LAST:event_btnListadosdeCuentasMouseEntered

    private void btnListadosdeCuentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListadosdeCuentasMouseExited
        btnListadosdeCuentas.setBackground(new Color(255,204,102));
    }//GEN-LAST:event_btnListadosdeCuentasMouseExited

    private void btnActualizarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarCuentaMouseClicked
        frmActualizarCuenta ventana= new frmActualizarCuenta();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnActualizarCuentaMouseClicked

    private void btnEliminarCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCuentasMouseClicked
    frmEliminarCuentas ventana= new frmEliminarCuentas();
    ventana.setVisible(true);
    }//GEN-LAST:event_btnEliminarCuentasMouseClicked

    private void btnListadoDeCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListadoDeCuentasMouseClicked
        frmListadoCuentas ventana= new frmListadoCuentas();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnListadoDeCuentasMouseClicked

    private void btnNuevoMovimiento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMovimiento1MouseClicked
        frmNuevoMovimiento ventana= new frmNuevoMovimiento();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnNuevoMovimiento1MouseClicked

    private void btnCerrarAplicacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarAplicacionMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();        
    }//GEN-LAST:event_btnCerrarAplicacionMousePressed

    private void btnCerrarAplicacionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarAplicacionMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);        
    }//GEN-LAST:event_btnCerrarAplicacionMouseDragged

    private void btnConexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConexionMouseClicked
        frmConexion ventana= new frmConexion();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnConexionMouseClicked

    private void btnMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovimientosMouseClicked
        frmMoviimientos ventana= new frmMoviimientos();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMovimientosMouseClicked

    private void btnEditarMovimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMovimientoMouseClicked
        frmEditarMovimientos ventana= new frmEditarMovimientos();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnEditarMovimientoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuentaAhorros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCuentaAhorros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPrincipal;
    private javax.swing.JPanel btnActualizarCuenta;
    private javax.swing.JLabel btnActualizarCuenta1;
    private javax.swing.JPanel btnCerrarAplicacion;
    private javax.swing.JPanel btnCerrarApp;
    private javax.swing.JLabel btnCerrarApp1;
    private javax.swing.JPanel btnConexion;
    private javax.swing.JPanel btnEditarMovimiento;
    private javax.swing.JPanel btnEliminarCuenta;
    private javax.swing.JLabel btnEliminarCuentas;
    private javax.swing.JLabel btnListadoDeCuentas;
    private javax.swing.JPanel btnListadosdeCuentas;
    private javax.swing.JPanel btnMovimientos;
    private javax.swing.JPanel btnNuevoMovimiento;
    private javax.swing.JLabel btnNuevoMovimiento1;
    private javax.swing.JPanel btnRegistroCuenta;
    private javax.swing.JLabel btnRegistroCuenta1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblConexion;
    private javax.swing.JLabel lblEditarMovimiento;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMovimiento;
    private javax.swing.JPanel panelDeOpciones;
    // End of variables declaration//GEN-END:variables
}
