/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Utilidades.DecimalDocumentFilter;
import Utilidades.LongitudDocumentFilter;
import Utilidades.SoloLetrasDocumentFilter;
import java.awt.Color;

import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

import SQL.Cuenta;

/**
 *
 * @author Jesus
 */
public class frmEliminarCuentas extends javax.swing.JFrame {
    int xMouse, yMouse;

    /**
     * Creates new form frmEliminarCuentas
     */
    public frmEliminarCuentas() {
        initComponents();
        //Activar las validaciones.
        ((AbstractDocument) this.txtCapitalDelete.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10,2));
        ((AbstractDocument) this.txtNombreDelete.getDocument()).setDocumentFilter(new SoloLetrasDocumentFilter(20));
        ((AbstractDocument) this.txtApellidoP.getDocument()).setDocumentFilter(new SoloLetrasDocumentFilter(20));
        ((AbstractDocument) this.txtApellidoM.getDocument()).setDocumentFilter(new SoloLetrasDocumentFilter(20));
        ((AbstractDocument) this.txtEmailDelete.getDocument()).setDocumentFilter(new LongitudDocumentFilter(100)); 
        ((AbstractDocument) this.txtID.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10,2));
    }
    
        private void reiniciarCampos() {
        txtID.setText("Ingrese el ID:");
        txtID.setForeground(new Color(51,51,51));
        txtNombreDelete.setText("Ingrese el Nombre:");
        txtNombreDelete.setForeground(new Color(102,102,102));
        txtApellidoP.setText("Ingrese el Apellido Paterno:");
        txtApellidoP.setForeground(new Color(102,102,102));
        txtApellidoM.setText("Ingrese el Apellido Materno:");
        txtApellidoM.setForeground(new Color(102,102,102));
        txtEmailDelete.setText("Ingrese el Email:");
        txtEmailDelete.setForeground(new Color(102,102,102));
        txtCapitalDelete.setText("Ingrese su Capital:");
        txtCapitalDelete.setForeground(new Color(51,51,51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundEliminarCuentas = new javax.swing.JPanel();
        barraNombreDelaSeccion = new javax.swing.JPanel();
        cabezaDeInterfaz = new javax.swing.JPanel();
        botonDeCierre = new javax.swing.JPanel();
        txtCierreDelete = new javax.swing.JLabel();
        txtNombreDelaSección = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCapitalDelete = new javax.swing.JLabel();
        txtCapitalDelete = new javax.swing.JTextField();
        spCapitalDelete = new javax.swing.JSeparator();
        lblNombreDelete = new javax.swing.JLabel();
        txtNombreDelete = new javax.swing.JTextField();
        spNombreDelete = new javax.swing.JSeparator();
        lblApellidoPaterno = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        spApellidoPaterno = new javax.swing.JSeparator();
        lblApellidoM = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        spApellidoM = new javax.swing.JSeparator();
        lblEmailDelete = new javax.swing.JLabel();
        txtEmailDelete = new javax.swing.JTextField();
        spEmailDelete = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JPanel();
        lblEliminar = new javax.swing.JLabel();
        btnCancelarDeletePanel = new javax.swing.JPanel();
        btnCancelarDelete = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        backgroundEliminarCuentas.setBackground(new java.awt.Color(255, 255, 255));
        backgroundEliminarCuentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraNombreDelaSeccion.setBackground(new java.awt.Color(255, 204, 102));

        cabezaDeInterfaz.setBackground(new java.awt.Color(255, 204, 102));
        cabezaDeInterfaz.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cabezaDeInterfazMouseDragged(evt);
            }
        });
        cabezaDeInterfaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cabezaDeInterfazMousePressed(evt);
            }
        });

        botonDeCierre.setBackground(new java.awt.Color(255, 204, 102));
        botonDeCierre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDeCierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDeCierreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonDeCierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonDeCierreMouseExited(evt);
            }
        });

        txtCierreDelete.setBackground(new java.awt.Color(255, 204, 102));
        txtCierreDelete.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCierreDelete.setForeground(new java.awt.Color(255, 255, 255));
        txtCierreDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCierreDelete.setText("X");
        txtCierreDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botonDeCierreLayout = new javax.swing.GroupLayout(botonDeCierre);
        botonDeCierre.setLayout(botonDeCierreLayout);
        botonDeCierreLayout.setHorizontalGroup(
            botonDeCierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCierreDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        botonDeCierreLayout.setVerticalGroup(
            botonDeCierreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCierreDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        txtNombreDelaSección.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        txtNombreDelaSección.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreDelaSección.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreDelaSección.setText("ELIMINAR CUENTAS");

        javax.swing.GroupLayout cabezaDeInterfazLayout = new javax.swing.GroupLayout(cabezaDeInterfaz);
        cabezaDeInterfaz.setLayout(cabezaDeInterfazLayout);
        cabezaDeInterfazLayout.setHorizontalGroup(
            cabezaDeInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabezaDeInterfazLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonDeCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabezaDeInterfazLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNombreDelaSección, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        cabezaDeInterfazLayout.setVerticalGroup(
            cabezaDeInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezaDeInterfazLayout.createSequentialGroup()
                .addComponent(botonDeCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreDelaSección, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout barraNombreDelaSeccionLayout = new javax.swing.GroupLayout(barraNombreDelaSeccion);
        barraNombreDelaSeccion.setLayout(barraNombreDelaSeccionLayout);
        barraNombreDelaSeccionLayout.setHorizontalGroup(
            barraNombreDelaSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabezaDeInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        barraNombreDelaSeccionLayout.setVerticalGroup(
            barraNombreDelaSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraNombreDelaSeccionLayout.createSequentialGroup()
                .addComponent(cabezaDeInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        backgroundEliminarCuentas.add(barraNombreDelaSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acountdelete.png"))); // NOI18N
        backgroundEliminarCuentas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 80, 80));

        lblCapitalDelete.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblCapitalDelete.setText("Capital:");
        backgroundEliminarCuentas.add(lblCapitalDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, -1, -1));

        txtCapitalDelete.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCapitalDelete.setForeground(new java.awt.Color(51, 51, 51));
        txtCapitalDelete.setBorder(null);
        txtCapitalDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapitalDeleteActionPerformed(evt);
            }
        });
        backgroundEliminarCuentas.add(txtCapitalDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 710, 390, 20));

        spCapitalDelete.setBackground(new java.awt.Color(0, 0, 0));
        backgroundEliminarCuentas.add(spCapitalDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 740, 400, 20));

        lblNombreDelete.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblNombreDelete.setText("Nombre:");
        backgroundEliminarCuentas.add(lblNombreDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        txtNombreDelete.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNombreDelete.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreDelete.setText("\n");
        txtNombreDelete.setBorder(null);
        txtNombreDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreDeleteMousePressed(evt);
            }
        });
        backgroundEliminarCuentas.add(txtNombreDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 390, -1));

        spNombreDelete.setBackground(new java.awt.Color(0, 0, 0));
        backgroundEliminarCuentas.add(spNombreDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 400, 20));

        lblApellidoPaterno.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblApellidoPaterno.setText("Apellido Paterno:");
        backgroundEliminarCuentas.add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        txtApellidoP.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtApellidoP.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidoP.setBorder(null);
        txtApellidoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoPMousePressed(evt);
            }
        });
        backgroundEliminarCuentas.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 390, 20));

        spApellidoPaterno.setBackground(new java.awt.Color(0, 0, 0));
        backgroundEliminarCuentas.add(spApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 400, 20));

        lblApellidoM.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblApellidoM.setText("Apellido Materno:");
        backgroundEliminarCuentas.add(lblApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        txtApellidoM.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtApellidoM.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidoM.setBorder(null);
        backgroundEliminarCuentas.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 390, 20));

        spApellidoM.setBackground(new java.awt.Color(0, 0, 0));
        backgroundEliminarCuentas.add(spApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 400, 20));

        lblEmailDelete.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblEmailDelete.setText("Email:");
        backgroundEliminarCuentas.add(lblEmailDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, -1, -1));

        txtEmailDelete.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtEmailDelete.setForeground(new java.awt.Color(102, 102, 102));
        txtEmailDelete.setBorder(null);
        txtEmailDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailDeleteActionPerformed(evt);
            }
        });
        backgroundEliminarCuentas.add(txtEmailDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 390, 20));

        spEmailDelete.setBackground(new java.awt.Color(0, 0, 0));
        backgroundEliminarCuentas.add(spEmailDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 400, 20));

        btnEliminar.setBackground(new java.awt.Color(255, 186, 21));
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        lblEliminar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("Eliminar");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        backgroundEliminarCuentas.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 790, 180, 50));

        btnCancelarDeletePanel.setBackground(new java.awt.Color(255, 186, 21));
        btnCancelarDeletePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelarDeletePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarDeletePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarDeletePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarDeletePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarDeletePanelMouseExited(evt);
            }
        });

        btnCancelarDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarDelete.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnCancelarDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarDelete.setText("Cancelar");

        javax.swing.GroupLayout btnCancelarDeletePanelLayout = new javax.swing.GroupLayout(btnCancelarDeletePanel);
        btnCancelarDeletePanel.setLayout(btnCancelarDeletePanelLayout);
        btnCancelarDeletePanelLayout.setHorizontalGroup(
            btnCancelarDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelarDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnCancelarDeletePanelLayout.setVerticalGroup(
            btnCancelarDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelarDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        backgroundEliminarCuentas.add(btnCancelarDeletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 790, -1, -1));

        lblId.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblId.setText("ID:");
        backgroundEliminarCuentas.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        txtID.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        backgroundEliminarCuentas.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 210, -1));

        btnSearch.setBackground(new java.awt.Color(255, 204, 102));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSearchLayout = new javax.swing.GroupLayout(btnSearch);
        btnSearch.setLayout(btnSearchLayout);
        btnSearchLayout.setHorizontalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnSearchLayout.setVerticalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        backgroundEliminarCuentas.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backgroundEliminarCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundEliminarCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCapitalDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapitalDeleteActionPerformed
    }//GEN-LAST:event_txtCapitalDeleteActionPerformed

    private void txtEmailDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailDeleteActionPerformed
    }//GEN-LAST:event_txtEmailDeleteActionPerformed

    private void cabezaDeInterfazMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabezaDeInterfazMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();    
    }//GEN-LAST:event_cabezaDeInterfazMousePressed

    private void cabezaDeInterfazMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabezaDeInterfazMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);        
    }//GEN-LAST:event_cabezaDeInterfazMouseDragged

    private void botonDeCierreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeCierreMouseClicked
    this.dispose();
    }//GEN-LAST:event_botonDeCierreMouseClicked

    private void botonDeCierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeCierreMouseEntered
        botonDeCierre.setBackground(Color.RED);
        txtCierreDelete.setBackground(Color.WHITE);        
    }//GEN-LAST:event_botonDeCierreMouseEntered

    private void botonDeCierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeCierreMouseExited
        botonDeCierre.setBackground(new Color(255,204,102));
        txtCierreDelete.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonDeCierreMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(255,69,0));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(new Color(255, 186, 21));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnCancelarDeletePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarDeletePanelMouseEntered
        btnCancelarDeletePanel.setBackground(new Color(255,69,0));
    }//GEN-LAST:event_btnCancelarDeletePanelMouseEntered

    private void btnCancelarDeletePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarDeletePanelMouseExited
        btnCancelarDeletePanel.setBackground(new Color(255, 186, 21));
    }//GEN-LAST:event_btnCancelarDeletePanelMouseExited

    private void txtNombreDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreDeleteMousePressed
       if(txtNombreDelete.getText().equals("Ingrese su Nombre:")){
        txtNombreDelete.setText("");
        txtNombreDelete.setForeground(Color.BLACK);
       }
       if(txtApellidoP.getText().equals("Ingrese su Apellido Paterno:")){
        txtApellidoP.setText("Ingrese su Apellido Paterno:");
        txtApellidoP.setForeground(Color.gray);
       }
       if(txtApellidoM.getText().equals("Ingrese su Apellido Materno:")){
        txtApellidoM.setText("Ingrese su Apellido Materno:");
        txtApellidoM.setForeground(Color.gray);
       }
       if(txtEmailDelete.getText().equals("Ingrese el Email:")){
        txtEmailDelete.setText("Ingrese el Email:");
        txtEmailDelete.setForeground(Color.gray);
       }
       if(txtCapitalDelete.getText().equals("Ingrese su Capital:")){
        txtCapitalDelete.setText("Ingrese su Capital:"); 
        txtCapitalDelete.setForeground(Color.gray);
       }            
    }//GEN-LAST:event_txtNombreDeleteMousePressed

    private void txtApellidoPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPMousePressed
       if(txtNombreDelete.getText().equals("Ingrese su Nombre:")){
        txtNombreDelete.setText("Ingrese su Nombre:");
        txtNombreDelete.setForeground(Color.BLACK);
       }
       if(txtApellidoP.getText().equals("Ingrese su Apellido Paterno:")){
        txtApellidoP.setText("");
        txtApellidoP.setForeground(Color.black);
       }
       if(txtApellidoM.getText().equals("Ingrese su Apellido Materno:")){
        txtApellidoM.setText("Ingrese su Apellido Materno:");
        txtApellidoM.setForeground(Color.gray);
       }
       if(txtEmailDelete.getText().equals("Ingrese el Email:")){
        txtEmailDelete.setText("Ingrese el Email:");
        txtEmailDelete.setForeground(Color.gray);
       }
       if(txtCapitalDelete.getText().equals("Ingrese su Capital:")){
        txtCapitalDelete.setText("Ingrese su Capital:"); 
        txtCapitalDelete.setForeground(Color.gray);
       }           
    }//GEN-LAST:event_txtApellidoPMousePressed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        btnSearch.setBackground(new Color(255,69,0));
    }//GEN-LAST:event_lblSearchMouseEntered

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        btnSearch.setBackground(new Color(255,69,0));
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        btnSearch.setBackground(new Color(255, 186, 21));
    }//GEN-LAST:event_btnSearchMouseExited

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        btnSearch.setBackground(new Color(255, 186, 21));
    }//GEN-LAST:event_lblSearchMouseExited

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        if(txtID.getText().trim().isEmpty() || txtID.getText().equals("Ingrese el ID:")){
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID para eliminar.", "Eliminar cuenta", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idEliminar;
        try {
            idEliminar = Integer.parseInt(txtID.getText().trim());
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID ingresado no es válido.", "Eliminar cuenta", JOptionPane.ERROR_MESSAGE);
            txtID.requestFocus();
            txtID.selectAll();
            return;
        }
        
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar la cuenta?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if(confirmar == JOptionPane.YES_OPTION) {
            Cuenta cuenta = new Cuenta();
            cuenta.setIdCuenta(idEliminar);
            if(cuenta.eliminar()) {
                JOptionPane.showMessageDialog(this, "Cuenta eliminada exitosamente.", "Eliminar cuenta", JOptionPane.INFORMATION_MESSAGE);
                reiniciarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al eliminar la cuenta.", "Eliminar cuenta", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if(txtID.getText().trim().isEmpty() || txtID.getText().equals("Ingrese el ID:")){
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID para eliminar.", "Eliminar cuenta", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idEliminar;
        try {
            idEliminar = Integer.parseInt(txtID.getText().trim());
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID ingresado no es válido.", "Eliminar cuenta", JOptionPane.ERROR_MESSAGE);
            txtID.requestFocus();
            txtID.selectAll();
            return;
        }
        
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar la cuenta?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if(confirmar == JOptionPane.YES_OPTION) {
            Cuenta cuenta = new Cuenta();
            cuenta.setIdCuenta(idEliminar);
            if(cuenta.eliminar()) {
                JOptionPane.showMessageDialog(this, "Cuenta eliminada exitosamente.", "Eliminar cuenta", JOptionPane.INFORMATION_MESSAGE);
                reiniciarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al eliminar la cuenta.", "Eliminar cuenta", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnCancelarDeletePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarDeletePanelMouseClicked
        reiniciarCampos();        
    }//GEN-LAST:event_btnCancelarDeletePanelMouseClicked

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        if(txtID.getText().trim().isEmpty() || txtID.getText().equals("Ingrese el ID:")){
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID para buscar.", "Buscar cuenta", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idBusqueda;
        try {
            idBusqueda = Integer.parseInt(txtID.getText().trim());
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID ingresado no es válido.", "Buscar cuenta", JOptionPane.ERROR_MESSAGE);
            txtID.requestFocus();
            txtID.selectAll();
            return;
        }
        
        Cuenta cuenta = new Cuenta();
        cuenta.setIdCuenta(idBusqueda);
        if(cuenta.buscar()){
            txtNombreDelete.setText(cuenta.getNombre());
            txtApellidoP.setText(cuenta.getApellidoPaterno());
            txtApellidoM.setText(cuenta.getApellidoMaterno());
            txtEmailDelete.setText(cuenta.getEmail());
            txtCapitalDelete.setText(String.valueOf(cuenta.getCapital()));
        } else {
            JOptionPane.showMessageDialog(this, "Cuenta no encontrada.", "Buscar cuenta", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_lblSearchMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        if(txtID.getText().trim().isEmpty() || txtID.getText().equals("Ingrese el ID:")){
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID para buscar.", "Buscar cuenta", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idBusqueda;
        try {
            idBusqueda = Integer.parseInt(txtID.getText().trim());
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID ingresado no es válido.", "Buscar cuenta", JOptionPane.ERROR_MESSAGE);
            txtID.requestFocus();
            txtID.selectAll();
            return;
        }
        
        Cuenta cuenta = new Cuenta();
        cuenta.setIdCuenta(idBusqueda);
        if(cuenta.buscar()){
            txtNombreDelete.setText(cuenta.getNombre());
            txtApellidoP.setText(cuenta.getApellidoPaterno());
            txtApellidoM.setText(cuenta.getApellidoMaterno());
            txtEmailDelete.setText(cuenta.getEmail());
            txtCapitalDelete.setText(String.valueOf(cuenta.getCapital()));
        } else {
            JOptionPane.showMessageDialog(this, "Cuenta no encontrada.", "Buscar cuenta", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnSearchMouseClicked

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEliminarCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundEliminarCuentas;
    private javax.swing.JPanel barraNombreDelaSeccion;
    private javax.swing.JPanel botonDeCierre;
    private javax.swing.JLabel btnCancelarDelete;
    private javax.swing.JPanel btnCancelarDeletePanel;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnSearch;
    private javax.swing.JPanel cabezaDeInterfaz;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblCapitalDelete;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblEmailDelete;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombreDelete;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JSeparator spApellidoM;
    private javax.swing.JSeparator spApellidoPaterno;
    private javax.swing.JSeparator spCapitalDelete;
    private javax.swing.JSeparator spEmailDelete;
    private javax.swing.JSeparator spNombreDelete;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCapitalDelete;
    private javax.swing.JLabel txtCierreDelete;
    private javax.swing.JTextField txtEmailDelete;
    private javax.swing.JTextField txtID;
    private javax.swing.JLabel txtNombreDelaSección;
    private javax.swing.JTextField txtNombreDelete;
    // End of variables declaration//GEN-END:variables
}
