/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Utilidades.DecimalDocumentFilter;
import java.awt.Color;

import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

import SQL.Movimiento;

/**
 *
 * @author Jesus
 */
public class frmEditarMovimientos extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form frmEditarMovimientos
     */
    public frmEditarMovimientos() {
        initComponents();
        ((AbstractDocument) this.txtCuentaEdit.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10,2));
        ((AbstractDocument) this.txtCantidadMov.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10,2));
        ((AbstractDocument) this.txtBuscarCuentaList.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10, 2));
        initMutualExclusionCheckboxes();
    }

    private int selectedMovimientoId = 0;

    private void reiniciarCamposEdicion() {
    txtCuentaEdit.setText("");
    txtCantidadMov.setText("");
    txtFechaMov.setText("");
    cbDeposito.setSelected(false);
    cbRetiro.setSelected(false);
    selectedMovimientoId = 0;
}

private void initMutualExclusionCheckboxes() {
    cbDeposito.addActionListener(e -> {
        if(cbDeposito.isSelected()) {
            cbRetiro.setSelected(false);
        }
    });
    cbRetiro.addActionListener(e -> {
        if(cbRetiro.isSelected()) {
            cbDeposito.setSelected(false);
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundEditMov = new javax.swing.JPanel();
        backgroundListMov = new javax.swing.JPanel();
        lblListMov = new javax.swing.JLabel();
        lblCuentaList = new javax.swing.JLabel();
        txtBuscarCuentaList = new javax.swing.JTextField();
        btnBuscarCuentaList = new javax.swing.JPanel();
        lblBuscarAcount = new javax.swing.JLabel();
        sPListMov = new javax.swing.JScrollPane();
        tbListMovimiento = new javax.swing.JTable();
        lblEditarMovimientos = new javax.swing.JLabel();
        txtCuentaEdit = new javax.swing.JTextField();
        txtTipo = new javax.swing.JLabel();
        cbRetiro = new javax.swing.JCheckBox();
        cbDeposito = new javax.swing.JCheckBox();
        lblCantidadMov = new javax.swing.JLabel();
        txtCantidadMov = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFechaMov = new javax.swing.JTextField();
        btnGuardarEditMov = new javax.swing.JPanel();
        btnGuardarEditMov1 = new javax.swing.JLabel();
        btnEditCancelarEdit = new javax.swing.JPanel();
        btnCancelarEditMov = new javax.swing.JLabel();
        pHead = new javax.swing.JPanel();
        btnSalirEditMov = new javax.swing.JPanel();
        lblSalirEditMov = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        backgroundEditMov.setBackground(new java.awt.Color(255, 255, 255));
        backgroundEditMov.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundListMov.setBackground(new java.awt.Color(51, 0, 204));

        lblListMov.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblListMov.setForeground(new java.awt.Color(255, 255, 255));
        lblListMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListMov.setText("Listado de Movimientos");

        lblCuentaList.setBackground(new java.awt.Color(255, 255, 255));
        lblCuentaList.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCuentaList.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaList.setText("Cuenta:");

        txtBuscarCuentaList.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        btnBuscarCuentaList.setBackground(new java.awt.Color(153, 0, 204));
        btnBuscarCuentaList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCuentaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCuentaListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarCuentaListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarCuentaListMouseExited(evt);
            }
        });

        lblBuscarAcount.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblBuscarAcount.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarAcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarAcount.setText("Buscar");

        javax.swing.GroupLayout btnBuscarCuentaListLayout = new javax.swing.GroupLayout(btnBuscarCuentaList);
        btnBuscarCuentaList.setLayout(btnBuscarCuentaListLayout);
        btnBuscarCuentaListLayout.setHorizontalGroup(
            btnBuscarCuentaListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscarAcount, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
        btnBuscarCuentaListLayout.setVerticalGroup(
            btnBuscarCuentaListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuscarAcount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sPListMov.setBorder(null);

        tbListMovimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "FECHA", "TIPO", "CANTIDAD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbListMovimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListMovimientoMouseClicked(evt);
            }
        });
        sPListMov.setViewportView(tbListMovimiento);

        javax.swing.GroupLayout backgroundListMovLayout = new javax.swing.GroupLayout(backgroundListMov);
        backgroundListMov.setLayout(backgroundListMovLayout);
        backgroundListMovLayout.setHorizontalGroup(
            backgroundListMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundListMovLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundListMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundListMovLayout.createSequentialGroup()
                        .addComponent(txtBuscarCuentaList, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCuentaList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCuentaList)
                    .addComponent(lblListMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sPListMov, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        backgroundListMovLayout.setVerticalGroup(
            backgroundListMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundListMovLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblListMov)
                .addGap(32, 32, 32)
                .addComponent(lblCuentaList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundListMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarCuentaList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscarCuentaList))
                .addGap(30, 30, 30)
                .addComponent(sPListMov, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );

        backgroundEditMov.add(backgroundListMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        lblEditarMovimientos.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblEditarMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditarMovimientos.setText("Editar Movimientos");
        backgroundEditMov.add(lblEditarMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 330, -1));

        txtCuentaEdit.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        backgroundEditMov.add(txtCuentaEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 160, -1));

        txtTipo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        txtTipo.setText("Tipo:");
        backgroundEditMov.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        cbRetiro.setBackground(new java.awt.Color(255, 255, 255));
        cbRetiro.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbRetiro.setText("Retiro");
        cbRetiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backgroundEditMov.add(cbRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        cbDeposito.setBackground(new java.awt.Color(255, 255, 255));
        cbDeposito.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbDeposito.setText("Depósito");
        cbDeposito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backgroundEditMov.add(cbDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        lblCantidadMov.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCantidadMov.setText("Cantidad:");
        backgroundEditMov.add(lblCantidadMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        txtCantidadMov.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        backgroundEditMov.add(txtCantidadMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 160, -1));

        lblFecha.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblFecha.setText("Fecha:");
        backgroundEditMov.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        txtFechaMov.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        backgroundEditMov.add(txtFechaMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 160, -1));

        btnGuardarEditMov.setBackground(new java.awt.Color(51, 51, 255));
        btnGuardarEditMov.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        btnGuardarEditMov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarEditMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarEditMovMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarEditMovMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarEditMovMouseExited(evt);
            }
        });

        btnGuardarEditMov1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnGuardarEditMov1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEditMov1.setText("Guardar");

        javax.swing.GroupLayout btnGuardarEditMovLayout = new javax.swing.GroupLayout(btnGuardarEditMov);
        btnGuardarEditMov.setLayout(btnGuardarEditMovLayout);
        btnGuardarEditMovLayout.setHorizontalGroup(
            btnGuardarEditMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarEditMovLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(btnGuardarEditMov1)
                .addGap(121, 121, 121))
        );
        btnGuardarEditMovLayout.setVerticalGroup(
            btnGuardarEditMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarEditMovLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardarEditMov1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        backgroundEditMov.add(btnGuardarEditMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 320, 50));

        btnEditCancelarEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        btnEditCancelarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditCancelarEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCancelarEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCancelarEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCancelarEditMouseExited(evt);
            }
        });

        btnCancelarEditMov.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnCancelarEditMov.setText("Cancelar");

        javax.swing.GroupLayout btnEditCancelarEditLayout = new javax.swing.GroupLayout(btnEditCancelarEdit);
        btnEditCancelarEdit.setLayout(btnEditCancelarEditLayout);
        btnEditCancelarEditLayout.setHorizontalGroup(
            btnEditCancelarEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditCancelarEditLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(btnCancelarEditMov)
                .addGap(117, 117, 117))
        );
        btnEditCancelarEditLayout.setVerticalGroup(
            btnEditCancelarEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditCancelarEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelarEditMov, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        backgroundEditMov.add(btnEditCancelarEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 320, 50));

        pHead.setBackground(new java.awt.Color(255, 255, 255));
        pHead.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pHeadMouseDragged(evt);
            }
        });
        pHead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pHeadMousePressed(evt);
            }
        });

        btnSalirEditMov.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirEditMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirEditMovMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirEditMovMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirEditMovMouseExited(evt);
            }
        });

        lblSalirEditMov.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSalirEditMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalirEditMov.setText("X");

        javax.swing.GroupLayout btnSalirEditMovLayout = new javax.swing.GroupLayout(btnSalirEditMov);
        btnSalirEditMov.setLayout(btnSalirEditMovLayout);
        btnSalirEditMovLayout.setHorizontalGroup(
            btnSalirEditMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalirEditMov, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        btnSalirEditMovLayout.setVerticalGroup(
            btnSalirEditMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalirEditMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pHeadLayout = new javax.swing.GroupLayout(pHead);
        pHead.setLayout(pHeadLayout);
        pHeadLayout.setHorizontalGroup(
            pHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHeadLayout.createSequentialGroup()
                .addGap(0, 361, Short.MAX_VALUE)
                .addComponent(btnSalirEditMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pHeadLayout.setVerticalGroup(
            pHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeadLayout.createSequentialGroup()
                .addComponent(btnSalirEditMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        backgroundEditMov.add(pHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 410, 30));

        lblCuenta.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCuenta.setText("Cuenta:");
        backgroundEditMov.add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundEditMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundEditMov, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirEditMovMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirEditMovMouseEntered
        btnSalirEditMov.setBackground(Color.red);
        lblSalirEditMov.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSalirEditMovMouseEntered

    private void btnSalirEditMovMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirEditMovMouseExited
        btnSalirEditMov.setBackground(Color.WHITE);
        lblSalirEditMov.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnSalirEditMovMouseExited

    private void btnSalirEditMovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirEditMovMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirEditMovMouseClicked

    private void pHeadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHeadMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();          
    }//GEN-LAST:event_pHeadMousePressed

    private void pHeadMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHeadMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);          
    }//GEN-LAST:event_pHeadMouseDragged

    private void btnGuardarEditMovMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEditMovMouseEntered
        btnGuardarEditMov.setBackground(new Color(25,25,112));
        btnGuardarEditMov1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnGuardarEditMovMouseEntered

    private void btnGuardarEditMovMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEditMovMouseExited
        btnGuardarEditMov.setBackground(new Color(51,51,255));
        btnGuardarEditMov1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnGuardarEditMovMouseExited

    private void btnEditCancelarEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCancelarEditMouseEntered
        btnEditCancelarEdit.setBackground(new Color(119,136,153));
        btnCancelarEditMov.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnEditCancelarEditMouseEntered

    private void btnEditCancelarEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCancelarEditMouseExited
        btnEditCancelarEdit.setBackground(new Color(242,242,242));
        btnCancelarEditMov.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnEditCancelarEditMouseExited

    private void btnBuscarCuentaListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCuentaListMouseEntered
        btnBuscarCuentaList.setBackground(new Color(216, 191, 216));
        lblBuscarAcount.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBuscarCuentaListMouseEntered

    private void btnBuscarCuentaListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCuentaListMouseExited
        btnBuscarCuentaList.setBackground(new Color(153,0,204));
        lblBuscarAcount.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBuscarCuentaListMouseExited

    private void btnBuscarCuentaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCuentaListMouseClicked
    if(txtBuscarCuentaList.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el número de cuenta para buscar.", "Error", JOptionPane.ERROR_MESSAGE);
        txtBuscarCuentaList.requestFocus();
        return;
    }
    int idCuenta;
    try {
        idCuenta = Integer.parseInt(txtBuscarCuentaList.getText().trim());
    } catch(NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El número de cuenta debe ser un entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
        txtBuscarCuentaList.requestFocus();
        txtBuscarCuentaList.selectAll();
        return;
    }
    Movimiento mov = new Movimiento();
    javax.swing.table.DefaultTableModel modelo = mov.listadoPorCuenta(idCuenta);
    tbListMovimiento.setModel(modelo);
    selectedMovimientoId = 0;
    }//GEN-LAST:event_btnBuscarCuentaListMouseClicked

    private void tbListMovimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListMovimientoMouseClicked
        int fila = tbListMovimiento.getSelectedRow();
    if(fila != -1) {
        selectedMovimientoId = Integer.parseInt(tbListMovimiento.getValueAt(fila, 0).toString());
        txtCuentaEdit.setText(txtBuscarCuentaList.getText().trim());
        txtFechaMov.setText(tbListMovimiento.getValueAt(fila, 1).toString());
        String tipo = tbListMovimiento.getValueAt(fila, 2).toString();
        if(tipo.equalsIgnoreCase("D") || tipo.equalsIgnoreCase("Depósito")) {
            cbDeposito.setSelected(true);
            cbRetiro.setSelected(false);
        } else if(tipo.equalsIgnoreCase("R") || tipo.equalsIgnoreCase("Retiro")) {
            cbDeposito.setSelected(false);
            cbRetiro.setSelected(true);
        } else {
            cbDeposito.setSelected(false);
            cbRetiro.setSelected(false);
        }
        txtCantidadMov.setText(tbListMovimiento.getValueAt(fila, 3).toString());
    }
    }//GEN-LAST:event_tbListMovimientoMouseClicked

    private void btnGuardarEditMovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarEditMovMouseClicked
    if(selectedMovimientoId == 0) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un movimiento para editar.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        if(txtCantidadMov.getText().trim().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Ingrese la cantidad.", "Error", JOptionPane.ERROR_MESSAGE);
      txtCantidadMov.requestFocus();
      return;
    }
    double cantidad;
    try {
        cantidad = Double.parseDouble(txtCantidadMov.getText().trim());
    } catch(NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        txtCantidadMov.requestFocus();
        txtCantidadMov.selectAll();
        return;
    }
        String tipo = "";
    if(cbDeposito.isSelected() && !cbRetiro.isSelected()) {
        tipo = "D";
    } else if(cbRetiro.isSelected() && !cbDeposito.isSelected()) {
        tipo = "R";
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un tipo de movimiento (solamente uno).", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        Movimiento mov = new Movimiento();
    mov.setIdMovimiento(selectedMovimientoId);
    mov.setTipo(tipo);
    mov.setCantidad(cantidad);
    if(mov.actualizar()) {
        JOptionPane.showMessageDialog(this, "Movimiento actualizado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        btnBuscarCuentaListMouseClicked(null);
        reiniciarCamposEdicion();
    } else {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar el movimiento.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarEditMovMouseClicked

    private void btnEditCancelarEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCancelarEditMouseClicked

    reiniciarCamposEdicion();
    }//GEN-LAST:event_btnEditCancelarEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditarMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditarMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditarMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditarMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditarMovimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundEditMov;
    private javax.swing.JPanel backgroundListMov;
    private javax.swing.JPanel btnBuscarCuentaList;
    private javax.swing.JLabel btnCancelarEditMov;
    private javax.swing.JPanel btnEditCancelarEdit;
    private javax.swing.JPanel btnGuardarEditMov;
    private javax.swing.JLabel btnGuardarEditMov1;
    private javax.swing.JPanel btnSalirEditMov;
    private javax.swing.JCheckBox cbDeposito;
    private javax.swing.JCheckBox cbRetiro;
    private javax.swing.JLabel lblBuscarAcount;
    private javax.swing.JLabel lblCantidadMov;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblCuentaList;
    private javax.swing.JLabel lblEditarMovimientos;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblListMov;
    private javax.swing.JLabel lblSalirEditMov;
    private javax.swing.JPanel pHead;
    private javax.swing.JScrollPane sPListMov;
    private javax.swing.JTable tbListMovimiento;
    private javax.swing.JTextField txtBuscarCuentaList;
    private javax.swing.JTextField txtCantidadMov;
    private javax.swing.JTextField txtCuentaEdit;
    private javax.swing.JTextField txtFechaMov;
    private javax.swing.JLabel txtTipo;
    // End of variables declaration//GEN-END:variables
}
