/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import SQL.Movimiento;
import Utilidades.DecimalDocumentFilter;
import javax.swing.text.AbstractDocument;


/**
 *
 * @author Kleber
 */
public class frmMoviimientos extends javax.swing.JFrame {

   int xMouse, yMouse;

    /**
     * Creates new form frmMoviimientos
     */
    public frmMoviimientos() {
        initComponents();
        ((AbstractDocument) this.txtBuscarCuenta.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10,2));

    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPHeader = new javax.swing.JPanel();
        btnExitMov = new javax.swing.JPanel();
        btnTxtExitMov = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        iblCuenta = new javax.swing.JLabel();
        lblMovimientos1 = new javax.swing.JLabel();
        txtBuscarCuenta = new javax.swing.JTextField();
        btnBuscarMov = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        iblTotalDepositos = new javax.swing.JLabel();
        iblTotalRetiros = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChatGPT_Image_5_jun_2025__18_18_51-removebg-preview.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChatGPT_Image_5_jun_2025__18_18_51-removebg-preview.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChatGPT_Image_5_jun_2025__18_18_51-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(810, 840));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KLEBER DELETED ACOUNT");

        jPHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPHeaderMouseDragged(evt);
            }
        });
        jPHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPHeaderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPHeaderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPHeaderMousePressed(evt);
            }
        });

        btnExitMov.setBackground(new java.awt.Color(255, 255, 255));
        btnExitMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMovMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMovMouseExited(evt);
            }
        });

        btnTxtExitMov.setBackground(new java.awt.Color(255, 255, 255));
        btnTxtExitMov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTxtExitMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxtExitMov.setText("X");
        btnTxtExitMov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTxtExitMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTxtExitMovMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnExitMovLayout = new javax.swing.GroupLayout(btnExitMov);
        btnExitMov.setLayout(btnExitMovLayout);
        btnExitMovLayout.setHorizontalGroup(
            btnExitMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTxtExitMov, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        btnExitMovLayout.setVerticalGroup(
            btnExitMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTxtExitMov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPHeaderLayout = new javax.swing.GroupLayout(jPHeader);
        jPHeader.setLayout(jPHeaderLayout);
        jPHeaderLayout.setHorizontalGroup(
            jPHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExitMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPHeaderLayout.setVerticalGroup(
            jPHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExitMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        iblCuenta.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        iblCuenta.setText("Cuenta:");

        lblMovimientos1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblMovimientos1.setText("Movimientos");

        txtBuscarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCuentaActionPerformed(evt);
            }
        });

        btnBuscarMov.setBackground(new java.awt.Color(51, 102, 255));
        btnBuscarMov.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBuscarMov.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarMov.setText("Buscar");
        btnBuscarMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMovActionPerformed(evt);
            }
        });

        tblMovimientos.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha:", "Tipo", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMovimientos);

        btnEditar.setBackground(new java.awt.Color(51, 102, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");

        iblTotalDepositos.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        iblTotalDepositos.setText("Total Depositos:");

        iblTotalRetiros.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        iblTotalRetiros.setText("Total Retiros:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMovimientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarMov))
                    .addComponent(iblCuenta))
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEditar)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(iblTotalRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iblTotalDepositos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMovimientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iblCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMov, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iblTotalDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iblTotalRetiros)
                .addGap(44, 44, 44)
                .addComponent(btnEditar)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 524, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 776, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTxtExitMovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTxtExitMovMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnTxtExitMovMouseClicked

    private void btnExitMovMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMovMouseEntered
        btnExitMov.setBackground(Color.WHITE);
        btnTxtExitMov.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnExitMovMouseEntered

    private void btnExitMovMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMovMouseExited
        btnExitMov.setBackground(Color.RED);
        btnTxtExitMov.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnExitMovMouseExited

    private void jPHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        int xMouse = 0;
        int yMouse = 0;
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPHeaderMouseDragged

    private void jPHeaderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHeaderMouseEntered
        btnExitMov.setBackground(Color.RED);
        btnTxtExitMov.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPHeaderMouseEntered

    private void jPHeaderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHeaderMouseExited
        btnExitMov.setBackground(Color.WHITE);
        btnTxtExitMov.setBackground(Color.BLACK);
    }//GEN-LAST:event_jPHeaderMouseExited

    private void jPHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPHeaderMousePressed
    }//GEN-LAST:event_jPHeaderMousePressed

    private void txtBuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCuentaActionPerformed

    private void btnBuscarMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMovActionPerformed
    if (txtBuscarCuenta.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el número de cuenta para buscar.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        txtBuscarCuenta.requestFocus();
        return;
    }
    int idCuenta;
    try {
        idCuenta = Integer.parseInt(txtBuscarCuenta.getText().trim());
    } catch (NumberFormatException e) {
         JOptionPane.showMessageDialog(this, "El número de cuenta debe ser un entero válido.", 
                                       "Error", JOptionPane.ERROR_MESSAGE);
         txtBuscarCuenta.requestFocus();
         txtBuscarCuenta.selectAll();
         return;
    }   
    Movimiento mov = new Movimiento();
    DefaultTableModel modelo = mov.listadoPorCuenta(idCuenta);
    tblMovimientos.setModel(modelo);
      double totalDepositos = 0.0;
    double totalRetiros = 0.0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
        String tipo = modelo.getValueAt(i, 1).toString();
        double importe = 0.0;
        try {
            importe = Double.parseDouble(modelo.getValueAt(i, 2).toString());
        } catch (NumberFormatException ex) {
            System.err.println("Error parseando el importe: " + ex.getMessage());
        }
                if (tipo.equalsIgnoreCase("D") || tipo.equalsIgnoreCase("Depósito")) {
            totalDepositos += importe;
        }
        else if (tipo.equalsIgnoreCase("R") || tipo.equalsIgnoreCase("Retiro")) {
            totalRetiros += importe;
        }
    }
    iblTotalDepositos.setText("Total Depositos: " + totalDepositos);
    iblTotalRetiros.setText("Total Retiros: " + totalRetiros);
    }//GEN-LAST:event_btnBuscarMovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMoviimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMoviimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMoviimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMoviimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmMoviimientos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMov;
    private javax.swing.JButton btnEditar;
    private javax.swing.JPanel btnExitMov;
    private javax.swing.JLabel btnTxtExitMov;
    private javax.swing.JLabel iblCuenta;
    private javax.swing.JLabel iblTotalDepositos;
    private javax.swing.JLabel iblTotalRetiros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPHeader;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMovimientos1;
    private javax.swing.JTable tblMovimientos;
    private javax.swing.JTextField txtBuscarCuenta;
    // End of variables declaration//GEN-END:variables

   
}
