/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;

import javax.swing.JOptionPane;

import SQL.Movimiento;
import Utilidades.DecimalDocumentFilter;
import Utilidades.LongitudDocumentFilter;
import Utilidades.SoloLetrasDocumentFilter;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Jesus
 */
public class frmNuevoMovimiento extends javax.swing.JFrame {
    int xMouse, yMouse;

    /**
     * Creates new form frmNuevoMovimiento
     */
    public frmNuevoMovimiento() {
        initComponents();
        ((AbstractDocument) this.txtCuenta.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10,2));
        ((AbstractDocument) this.txtImporte.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10,2));
    }
private void reiniciarCampos() {
    txtCuenta.setText("Ingrese su Cuenta:");
    txtCuenta.setForeground(new Color(102,102,102)); 

    txtImporte.setText("Ingrese su Importe:");
    txtImporte.setForeground(new Color(102,102,102));
    
    cbTipoMovimiento.setSelectedIndex(0);

    txtFechaMov.setText("Ingrese su Fecha:");
    txtFechaMov.setForeground(new Color(102,102,102));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        backNewMovement = new javax.swing.JPanel();
        logoMovement = new javax.swing.JLabel();
        lblNuevoMovimiento = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        lblImporte = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        cbTipoMovimiento = new javax.swing.JComboBox<>();
        lblTipo = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        sep2 = new javax.swing.JSeparator();
        btnExitMov = new javax.swing.JPanel();
        txtExitMov = new javax.swing.JLabel();
        btncabezamov = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        txtFechaMov = new javax.swing.JTextField();
        sep3 = new javax.swing.JSeparator();
        btnCancelarMov = new javax.swing.JPanel();
        lblCancelarMov = new javax.swing.JLabel();
        btnGuardarMov = new javax.swing.JPanel();
        lblGuardar = new javax.swing.JLabel();

        jTextField3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("Ingrese su Cuenta:");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        backNewMovement.setBackground(new java.awt.Color(255, 255, 255));
        backNewMovement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoMovement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newmovement.png"))); // NOI18N
        backNewMovement.add(logoMovement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        lblNuevoMovimiento.setFont(new java.awt.Font("Roboto Black", 0, 32)); // NOI18N
        lblNuevoMovimiento.setText("Nuevo Movimiento");
        backNewMovement.add(lblNuevoMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        lblCuenta.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblCuenta.setText("Cuenta:");
        backNewMovement.add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));
        backNewMovement.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 310, 10));

        lblImporte.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblImporte.setText("Importe:");
        backNewMovement.add(lblImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        txtImporte.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtImporte.setForeground(new java.awt.Color(102, 102, 102));
        txtImporte.setText("Ingrese su Importe:");
        txtImporte.setBorder(null);
        txtImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporteActionPerformed(evt);
            }
        });
        backNewMovement.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 300, 30));

        cbTipoMovimiento.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cbTipoMovimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Depósito", "Retiro" }));
        cbTipoMovimiento.setBorder(null);
        cbTipoMovimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbTipoMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoMovimientoActionPerformed(evt);
            }
        });
        backNewMovement.add(cbTipoMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 340, -1));

        lblTipo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblTipo.setText("Tipo:");
        backNewMovement.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        txtCuenta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCuenta.setForeground(new java.awt.Color(102, 102, 102));
        txtCuenta.setText("Ingrese su Cuenta:");
        txtCuenta.setBorder(null);
        backNewMovement.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 300, 30));
        backNewMovement.add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 310, 10));

        btnExitMov.setBackground(new java.awt.Color(255, 255, 255));
        btnExitMov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMovMouseClicked(evt);
            }
        });

        txtExitMov.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        txtExitMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExitMov.setText("X");

        javax.swing.GroupLayout btnExitMovLayout = new javax.swing.GroupLayout(btnExitMov);
        btnExitMov.setLayout(btnExitMovLayout);
        btnExitMovLayout.setHorizontalGroup(
            btnExitMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExitMov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnExitMovLayout.setVerticalGroup(
            btnExitMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExitMov, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        backNewMovement.add(btnExitMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 40));

        btncabezamov.setBackground(new java.awt.Color(255, 255, 255));
        btncabezamov.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btncabezamovMouseDragged(evt);
            }
        });
        btncabezamov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncabezamovMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btncabezamovLayout = new javax.swing.GroupLayout(btncabezamov);
        btncabezamov.setLayout(btncabezamovLayout);
        btncabezamovLayout.setHorizontalGroup(
            btncabezamovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        btncabezamovLayout.setVerticalGroup(
            btncabezamovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        backNewMovement.add(btncabezamov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        lblFecha.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblFecha.setText("Fecha:");
        backNewMovement.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        txtFechaMov.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtFechaMov.setForeground(new java.awt.Color(102, 102, 102));
        txtFechaMov.setText("Ingrese su Fecha:");
        txtFechaMov.setBorder(null);
        backNewMovement.add(txtFechaMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 300, 30));
        backNewMovement.add(sep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 310, 10));

        btnCancelarMov.setBackground(new java.awt.Color(255, 204, 51));
        btnCancelarMov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMovMouseClicked(evt);
            }
        });

        lblCancelarMov.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblCancelarMov.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelarMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelarMov.setText("Cancelar");

        javax.swing.GroupLayout btnCancelarMovLayout = new javax.swing.GroupLayout(btnCancelarMov);
        btnCancelarMov.setLayout(btnCancelarMovLayout);
        btnCancelarMovLayout.setHorizontalGroup(
            btnCancelarMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCancelarMov, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnCancelarMovLayout.setVerticalGroup(
            btnCancelarMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCancelarMov, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        backNewMovement.add(btnCancelarMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 120, 40));

        btnGuardarMov.setBackground(new java.awt.Color(255, 204, 51));
        btnGuardarMov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMovMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMovMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMovMouseExited(evt);
            }
        });

        lblGuardar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(255, 255, 255));
        lblGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuardar.setText("Guardar");
        lblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGuardarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarMovLayout = new javax.swing.GroupLayout(btnGuardarMov);
        btnGuardarMov.setLayout(btnGuardarMovLayout);
        btnGuardarMovLayout.setHorizontalGroup(
            btnGuardarMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnGuardarMovLayout.setVerticalGroup(
            btnGuardarMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        backNewMovement.add(btnGuardarMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backNewMovement, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backNewMovement, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoMovimientoActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void txtImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporteActionPerformed

    private void btnExitMovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMovMouseClicked
    this.dispose();       
    }//GEN-LAST:event_btnExitMovMouseClicked

    private void btncabezamovMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncabezamovMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();       
    }//GEN-LAST:event_btncabezamovMousePressed

    private void btncabezamovMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncabezamovMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);        
    }//GEN-LAST:event_btncabezamovMouseDragged

    private void lblGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseEntered
    }//GEN-LAST:event_lblGuardarMouseEntered

    private void btnGuardarMovMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMovMouseEntered
    btnGuardarMov.setBackground(Color.red);
    }//GEN-LAST:event_btnGuardarMovMouseEntered

    private void btnGuardarMovMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMovMouseExited
    btnGuardarMov.setBackground(new Color(255,204,51));        
    }//GEN-LAST:event_btnGuardarMovMouseExited

    private void btnGuardarMovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMovMouseClicked
    if (txtCuenta.getText().trim().isEmpty() || txtCuenta.getText().equals("Ingrese su Cuenta:")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el número de cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
        txtCuenta.requestFocus();
        return;
    }
    int idCuenta;
    try {
        idCuenta = Integer.parseInt(txtCuenta.getText().trim());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El número de cuenta debe ser un entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
        txtCuenta.requestFocus();
        txtCuenta.selectAll();
        return;
    }
    if (txtImporte.getText().trim().isEmpty() || txtImporte.getText().equals("Ingrese su Importe:")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el importe.", "Error", JOptionPane.ERROR_MESSAGE);
        txtImporte.requestFocus();
        return;
    }
    double importe;
    try {
        importe = Double.parseDouble(txtImporte.getText().trim());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El importe debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        txtImporte.requestFocus();
        txtImporte.selectAll();
        return;
    }
    String tipoSeleccionado = cbTipoMovimiento.getSelectedItem().toString();
    String tipo;
    if (tipoSeleccionado.equalsIgnoreCase("Depósito")) {
        tipo = "D";
    } else {
        tipo = "R";
    }
    Movimiento mov = new Movimiento();
    mov.setIdCuenta(idCuenta);
    mov.setTipo(tipo);
    mov.setCantidad(importe);
    if (mov.insertar()) {
        JOptionPane.showMessageDialog(this, "Movimiento registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        reiniciarCampos(); 
    } else {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el movimiento.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarMovMouseClicked

    private void btnCancelarMovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMovMouseClicked
        reiniciarCampos();
    }//GEN-LAST:event_btnCancelarMovMouseClicked

    private void lblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseClicked
         // Validar que se haya ingresado el número de cuenta
    if (txtCuenta.getText().trim().isEmpty() || txtCuenta.getText().equals("Ingrese su Cuenta:")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el número de cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
        txtCuenta.requestFocus();
        return;
    }
    
    int idCuenta;
    try {
        idCuenta = Integer.parseInt(txtCuenta.getText().trim());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El número de cuenta debe ser un entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
        txtCuenta.requestFocus();
        txtCuenta.selectAll();
        return;
    }
    
    // Validar que se haya ingresado el importe
    if (txtImporte.getText().trim().isEmpty() || txtImporte.getText().equals("Ingrese su Importe:")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese el importe.", "Error", JOptionPane.ERROR_MESSAGE);
        txtImporte.requestFocus();
        return;
    }
    
    double importe;
    try {
        importe = Double.parseDouble(txtImporte.getText().trim());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El importe debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        txtImporte.requestFocus();
        txtImporte.selectAll();
        return;
    }
    
    // Obtener el tipo de movimiento desde el combo: usamos "Depósito" y "Retiro"
    String tipoSeleccionado = cbTipoMovimiento.getSelectedItem().toString();
    String tipo;
    if (tipoSeleccionado.equalsIgnoreCase("Depósito")) {
        tipo = "D";
    } else {
        tipo = "R";
    }
    
    // Nota: El campo de fecha en la base de datos se establece automáticamente (CURRENT_TIMESTAMP)
    // por lo que no es indispensable usar txtFechaMov para la inserción.
    
    // Crear el objeto Movimiento con los datos ingresados
    Movimiento mov = new Movimiento();
    mov.setIdCuenta(idCuenta);
    mov.setTipo(tipo);
    mov.setCantidad(importe);
    // Si deseas asignar la fecha ingresada manualmente:
    // mov.setFecha(txtFechaMov.getText().trim());
    
    // Intentar insertar el movimiento en la base de datos
    if (mov.insertar()) {
        JOptionPane.showMessageDialog(this, "Movimiento registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        reiniciarCampos(); // Limpiar los campos para un nuevo registro
    } else {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el movimiento.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_lblGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNuevoMovimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backNewMovement;
    private javax.swing.JPanel btnCancelarMov;
    private javax.swing.JPanel btnExitMov;
    private javax.swing.JPanel btnGuardarMov;
    private javax.swing.JPanel btncabezamov;
    private javax.swing.JComboBox<String> cbTipoMovimiento;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblCancelarMov;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblNuevoMovimiento;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel logoMovement;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JLabel txtExitMov;
    private javax.swing.JTextField txtFechaMov;
    private javax.swing.JTextField txtImporte;
    // End of variables declaration//GEN-END:variables
}
